services:

###### SHARED BASELINE ######

  shared-ea-bn-weibo:
    profiles: [ "Shared", "weibo", "shared-weibo" ]
    extends:
      file: base.yml
      service: base-experiment
    container_name: shared-ea-freeze-bn-weibo
    command: "python src/Bruna/domain_adapt_eegshared_exp.py --model EEGNet --config config/config_weibo.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset Weibo2014 --remove_bn False --criterion_type CrossEntropyLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '1' ]
              capabilities: [ gpu ]

  shared-noea-bn-weibo:
    profiles: [ "Shared", "weibo", "shared-weibo" ]
    extends:
      file: base.yml
      service: base-experiment
    container_name: shared-noea-freeze-bn-weibo
    command: "python src/Bruna/domain_adapt_eegshared_exp.py --model EEGNet --config config/config_weibo.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset Weibo2014 --remove_bn False --criterion_type CrossEntropyLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '1' ]
              capabilities: [ gpu ]

  shared-ea-bn-bnci:
    profiles: ["Shared", "bnci"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: shared-ea-bn
    command: "python src/Bruna/domain_adapt_eegshared_exp.py --model EEGNetShared --config config/config.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset BNCI2014001 --remove_bn False --criterion_type CrossEntropyLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]
  shared-noea-bn-bnci:
    profiles: [ "Shared", "bnci"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: shared-noea-bn
    command: "python src/Bruna/domain_adapt_eegshared_exp.py --model EEGNetShared --config config/config.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset BNCI2014001 --remove_bn False --criterion_type CrossEntropyLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '1' ]
              capabilities: [ gpu ]

  shared-ea-bn-robin:
    profiles: ["Shared", "robin"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: shared-ea-bn
    command: "python src/Bruna/domain_adapt_eegshared_exp.py --model EEGNetShared --config config/config.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset Schirrmeister2017 --remove_bn False --criterion_type CrossEntropyLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]
  shared-noea-bn-robin:
    profiles: [ "Shared", "robin" ]
    extends:
      file: base.yml
      service: base-experiment
    container_name: shared-noea-bn
    command: "python src/Bruna/domain_adapt_eegshared_exp.py --model EEGNetShared --config config/config.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset Schirrmeister2017 --remove_bn False --criterion_type CrossEntropyLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '1' ]
              capabilities: [ gpu ]

######## HYBRID EA ##########

### BNCI
  hybrid-ea-bn-bnci:
    profiles: ["test", "EA", "Freeze", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-ea-bn
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset BNCI2014001 --remove_bn False --criterion_type CrossEntropyLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-ea-bn-bnci-inference:
    profiles: ["inf-hybrid", "EA", "Freeze", "Hybrid-BN", "shared-weibo"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-ea-bn-inf
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset BNCI2014001 --remove_bn False --criterion_type CrossEntropyLoss --mode Inference"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-ea-bn-bnci-loss:
    profiles: ["normal-hybrid-loss", "EA", "test-normal", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-ea-bn-loss
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset BNCI2014001 --remove_bn False --criterion_type AlignmentLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-ea-bn-bnci-loss-inf:
    profiles: ["normal-hybrid-loss", "EA", "test-normal", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-ea-bn-loss-inf
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset BNCI2014001 --remove_bn False --criterion_type AlignmentLoss --mode Inference"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-ea-bn-bnci-choose:
    profiles: ["choose-hybrid", "TEST", "Freeze", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-EA-bn-bnci-choose
    command: "python src/Bruna/domain_adapt_choosehead.py --model EEGNet --config config/config.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset BNCI2014001 --remove_bn False --criterion_type CrossEntropyLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-ea-bn-bnci-loss-choose:
    profiles: ["choose-hybrid", "normal-hybrid-loss", "test-normal", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-ea-freeze-bn-loss-choose
    command: "python src/Bruna/domain_adapt_choosehead.py --model EEGNet --config config/config.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset BNCI2014001 --remove_bn False --criterion_type AlignmentLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

#### ROBIN

  hybrid-ea-bn-robin:
    profiles: ["Hybrid-robin", "EA", "Freeze", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-ea-bn-robin
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset Schirrmeister2017 --remove_bn False --criterion_type CrossEntropyLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-ea-bn-robin-inferece:
    profiles: [ "inf-hybrid", "EA", "Freeze", "Hybrid-BN", "Hybrid-BN-EA" ]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-ea-bn-robin-inf
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset Schirrmeister2017 --remove_bn False --criterion_type CrossEntropyLoss --mode Inference"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '1' ]
              capabilities: [ gpu ]

  hybrid-ea-bn-robin-loss:
    profiles: ["hybrid-loss", "EA", "test-normal", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-ea-bn-robin-loss
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset Schirrmeister2017 --remove_bn False --criterion_type AlignmentLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-ea-bn-robin-loss-inf:
    profiles: ["hybrid-loss", "EA", "test-normal", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-ea-bn-robin-loss-inf
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset Schirrmeister2017 --remove_bn False --criterion_type AlignmentLoss --mode Inference"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]


  hybrid-ea-bn-robin-choose:
    profiles: ["choose-hybrid", "TEST", "Freeze", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-EA-bn-robin-choose
    command: "python src/Bruna/domain_adapt_choosehead.py --model EEGNet --config config/config.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset Schirrmeister2017 --remove_bn False --criterion_type CrossEntropyLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-ea-bn-robin-loss-choose:
    profiles: ["choose-hybrid", "hybrid-loss", "test-normal", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-ea-robin-bn-loss-choose
    command: "python src/Bruna/domain_adapt_choosehead.py --model EEGNet --config config/config.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset Schirrmeister2017 --remove_bn False --criterion_type AlignmentLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

###### WEIBO

  hybrid-ea-bn-weibo:
    profiles: ["Hybrid-weibo", "EA", "Freeze", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-ea-bn-weibo
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config_weibo.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset Weibo2014 --remove_bn False --criterion_type CrossEntropyLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-ea-bn-weibo-inference:
    profiles: ["inf-hybrid", "Hybrid-weibo", "Freeze", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-ea-bn-weibo-inf
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config_weibo.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset Weibo2014 --remove_bn False --criterion_type CrossEntropyLoss --mode Inference"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-ea-bn-weibo-loss:
    profiles: ["loss-hybrid-fit", "EA", "test-normal", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-ea-bn-weibo-loss
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config_weibo.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset Weibo2014 --remove_bn False --criterion_type AlignmentLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-ea-bn-weibo-loss-inf:
    profiles: ["loss-hybrid", "EA", "test-normal", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-ea-bn-weibo-loss-inf
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config_weibo.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset Weibo2014 --remove_bn False --criterion_type AlignmentLoss --mode Inference"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-ea-bn-weibo-choose:
    profiles: ["choose-hybrid", "Hybrid-weibo-choose", "Freeze", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-EA-bn-weibo-choose
    command: "python src/Bruna/domain_adapt_choosehead.py --model EEGNet --config config/config_weibo.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset Weibo2014 --remove_bn False --criterion_type CrossEntropyLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-ea-bn-weibo-loss-choose:
    profiles: ["loss-hybrid", "choose-hybrid-loss-wb", "test-normal", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-ea-weibo-bn-loss-choose
    command: "python src/Bruna/domain_adapt_choosehead.py --model EEGNet --config config/config_weibo.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset Weibo2014 --remove_bn False --criterion_type AlignmentLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-ea-bn-weibo-loss-choose-inf:
    profiles: ["loss-hybrid", "choose-hybrid-loss-wb", "test-normal", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-ea-weibo-bn-loss-choose-inf
    command: "python src/Bruna/domain_adapt_choosehead.py --model EEGNet --config config/config_weibo.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset Weibo2014 --remove_bn False --criterion_type AlignmentLoss --mode Inference"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]


###### SHIN

  hybrid-ea-bn-shin:
    profiles: ["Hybrid-shin", "EA", "Freeze", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-ea-bn-shin
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config_shin.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset Shin2017A --remove_bn False --criterion_type CrossEntropyLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-ea-bn-shin-inference:
    profiles: ["Hybrid-shin", "EA", "Freeze", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-ea-bn-shin-inf
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config_shin.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset Shin2017A --remove_bn False --criterion_type CrossEntropyLoss --mode Inference"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-ea-bn-shin-loss:
    profiles: ["Hybrid-shin-loss", "EA", "test-normal", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-ea-bn-shin-loss
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config_shin.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset Shin2017A --remove_bn False --criterion_type AlignmentLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-ea-bn-shin-choose:
    profiles: ["Hybrid-shin", "TEST", "Freeze", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-EA-bn-shin-choose
    command: "python src/Bruna/domain_adapt_choosehead.py --model EEGNet --config config/config_shin.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset Shin2017A --remove_bn False --criterion_type CrossEntropyLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-ea-bn-shin-loss-choose:
    profiles: ["Hybrid-shin-loss", "choose-hybrid-loss-wb", "test-normal", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-ea-shin-bn-loss-choose
    command: "python src/Bruna/domain_adapt_choosehead.py --model EEGNet --config config/config_shin.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset Shin2017A --remove_bn False --criterion_type AlignmentLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

######## HYBRID NOEA ##########
####  BNCI

  hybrid-noea-bn-bnci:
    profiles: ["test", "noEA", "Freeze", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-bn
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset BNCI2014001 --remove_bn False --criterion_type CrossEntropyLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-noea-bn-bnci-inference:
    profiles: ["inf-hybrid", "noEA", "Freeze", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-bn-inf
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset BNCI2014001 --remove_bn False --criterion_type CrossEntropyLoss --mode Inference"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-noea-bn-bnci-loss:
    profiles: ["normal-hybrid-loss", "EA", "test-normal", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-bn-loss
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset BNCI2014001 --remove_bn False --criterion_type AlignmentLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-noea-bn-bnci-loss-inf:
    profiles: ["normal-hybrid-loss", "EA", "test-normal", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-bn-loss-inf
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset BNCI2014001 --remove_bn False --criterion_type AlignmentLoss --mode Inference"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-noea-bn-bnci-choose:
    profiles: ["choose-hybrid", "choose-hybrid-noea", "Freeze", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-bn-bnci-choose
    command: "python src/Bruna/domain_adapt_choosehead.py --model EEGNet --config config/config.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset BNCI2014001 --remove_bn False --criterion_type CrossEntropyLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-noea-bn-bnci-loss-choose:
    profiles: ["choose-hybrid", "test-normal", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-freeze-bn-loss-choose
    command: "python src/Bruna/domain_adapt_choosehead.py --model EEGNet --config config/config.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset BNCI2014001 --remove_bn False --criterion_type AlignmentLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

#### ROBIN

  hybrid-noea-bn-robin:
    profiles: ["Hybrid-robin", "EA", "Freeze", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-bn-robin
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset Schirrmeister2017 --remove_bn False --criterion_type CrossEntropyLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-noea-bn-robin-inference:
    profiles: [ "inf-hybrid", "EA", "Freeze", "Hybrid-BN", "Hybrid-BN-EA" ]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-bn-robin-inf
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset Schirrmeister2017 --remove_bn False --criterion_type CrossEntropyLoss --mode Inference"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '1' ]
              capabilities: [ gpu ]

  hybrid-noea-bn-robin-loss:
    profiles: ["hybrid-loss", "EA", "test-normal", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-bn-robin-loss
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset Schirrmeister2017 --remove_bn False --criterion_type AlignmentLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-noea-bn-robin-loss-inf:
    profiles: ["hybrid-loss", "EA", "test-normal", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-bn-robin-loss-inf
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset Schirrmeister2017 --remove_bn False --criterion_type AlignmentLoss --mode Inference"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-noea-bn-robin-choose:
    profiles: ["choose-hybrid", "choose-hybrid-nore", "Freeze", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-bn-robin-choose
    command: "python src/Bruna/domain_adapt_choosehead.py --model EEGNet --config config/config.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset Schirrmeister2017 --remove_bn False --criterion_type CrossEntropyLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-noea-bn-robin-loss-choose:
    profiles: ["hybrid-loss", "EA", "test-normal", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-robin-bn-loss-choose
    command: "python src/Bruna/domain_adapt_choosehead.py --model EEGNet --config config/config.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset Schirrmeister2017 --remove_bn False --criterion_type AlignmentLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

###### WEIBO

  hybrid-noea-bn-weibo:
    profiles: ["Hybrid-weibo", "Freeze", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-bn-weibo
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config_weibo.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset Weibo2014 --remove_bn False --criterion_type CrossEntropyLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-noea-bn-weibo-inference:
    profiles: [ "inf-hybrid", "Hybrid-weibo", "Freeze", "Hybrid-BN", "Hybrid-BN-EA" ]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-bn-weibo-inf
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config_weibo.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset Weibo2014 --remove_bn False --criterion_type CrossEntropyLoss --mode Inference"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '1' ]
              capabilities: [ gpu ]

  hybrid-noea-bn-weibo-loss:
    profiles: ["loss-hybrid-fit", "EA", "test-normal", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-bnn-weibo-loss
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config_weibo.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset Weibo2014 --remove_bn False --criterion_type AlignmentLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-noea-bn-weibo-loss-inf:
    profiles: ["loss-hybrid", "EA", "test-normal", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-bn-weibo-loss-inf
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config_weibo.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset Weibo2014 --remove_bn False --criterion_type AlignmentLoss --mode Inference"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-noea-bn-weibo-choose:
    profiles: ["choose-hybrid", "Hybrid-weibo-choose", "Freeze", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-bn-weibo-choose
    command: "python src/Bruna/domain_adapt_choosehead.py --model EEGNet --config config/config_weibo.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset Weibo2014 --remove_bn False --criterion_type CrossEntropyLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-noea-bn-weibo-loss-choose:
    profiles: ["loss-hybrid", "choose-hybrid-loss", "test-normal", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-weibo-bn-loss-choose
    command: "python src/Bruna/domain_adapt_choosehead.py --model EEGNet --config config/config_weibo.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset Weibo2014 --remove_bn False --criterion_type AlignmentLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

######## SHIN

  hybrid-noea-bn-shin:
    profiles: ["Hybrid-shin", "EA", "Freeze", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-bn-shin
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config_shin.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset Shin2017A --remove_bn False --criterion_type CrossEntropyLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-noea-bn-shin-inference:
    profiles: [ "Hybrid-shin", "EA", "Freeze", "Hybrid-BN", "Hybrid-BN-EA" ]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-bn-shin-inf
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config_shin.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset Shin2017A --remove_bn False --criterion_type CrossEntropyLoss --mode Inference"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '1' ]
              capabilities: [ gpu ]

  hybrid-noea-bn-shin-loss:
    profiles: ["Hybrid-shin-loss", "EA", "test-normal", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-bn-shin-loss
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config_shin.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset Shin2017A --remove_bn False --criterion_type AlignmentLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-noea-bn-shin-choose:
    profiles: ["Hybrid-shin", "choose-hybrid-wb", "Freeze", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-bn-shin-choose
    command: "python src/Bruna/domain_adapt_choosehead.py --model EEGNet --config config/config_shin.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset Shin2017A --remove_bn False --criterion_type CrossEntropyLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-noea-bn-shin-loss-choose:
    profiles: ["Hybrid-shin-loss", "choose-hybrid-loss", "test-normal", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-shin-bn-loss-choose
    command: "python src/Bruna/domain_adapt_choosehead.py --model EEGNet --config config/config_shin.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset Shin2017A --remove_bn False --criterion_type AlignmentLoss"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]



  jupyter:
    profiles: ["jupyter"]
    user: "${MYUID}:${MYGID}"
    extends:
      file: base.yml
      service: base-experiment
    container_name: jupyter-host-eeg
    command: "jupyter notebook --no-browser"
    ports:
      - "9999:8888"
    environment:
      JUPYTER_TOKEN: "docker"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '1' ]
              capabilities: [ gpu ]

  shell:
    profiles: ["shell"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: debug-shell
    command: ["/bin/bash"]
    stdin_open: true

volumes:
  moabb-datasets:
    external: true
