services:

  hybrid-EA-freeze-bn:
    profiles: ["Hybrid", "EA", "Freeze", "BN", "Hybrid-BN", "Hybrid-BN-EA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-ea-freeze-bn
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset BNCI2014001 --remove_bn False"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-EA-freeze-nobn:
    profiles: ["Hybrid", "EA", "Freeze", "NoBN", "Hybrid-NoBN"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-ea-freeze-nobn
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset BNCI2014001 --remove_bn True"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-EA-freeze-onebn:
    profiles: ["Hybrid", "EA", "Freeze", "OneBN", "Hybrid-OneBN"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-ea-freeze-onebn
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset BNCI2014001 --remove_bn One-bn"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-EA-nofreeze-bn:
    profiles: ["Hybrid", "EA", "No-freeze", "BN", "Hybrid-BN"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-ea-nofreeze-bn
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea alignment --freeze no-freeze --num_exp exp_shared --dataset BNCI2014001 --remove_bn False"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-EA-nofreeze-nobn:
    profiles: ["Hybrid", "EA", "No-freeze", "NoBN", "Hybrid-NoBN"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-ea-nofreeze-nobn
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea alignment --freeze no-freeze --num_exp exp_shared --dataset BNCI2014001 --remove_bn True"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-EA-nofreeze-onebn:
    profiles: ["Hybrid", "EA", "No-freeze", "OneBN", "Hybrid-OneBN"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-ea-nofreeze-onebn
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea alignment --freeze no-freeze --num_exp exp_shared --dataset BNCI2014001 --remove_bn One-bn"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-noEA-freeze-bn:
    profiles: ["Hybrid", "No-EA", "freeze", "BN", "Hybrid-BN"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-freeze-bn
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset BNCI2014001 --remove_bn False"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-noEA-freeze-nobn:
    profiles: ["Hybrid", "No-EA", "freeze", "NoBN", "Hybrid-NoBN"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-freeze-nobn
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset BNCI2014001 --remove_bn True"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-noEA-freeze-onebn:
    profiles: ["Hybrid", "No-EA", "freeze", "OneBN", "Hybrid-OneBN"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-freeze-onebn
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset BNCI2014001 --remove_bn One-bn"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-noEA-nofreeze-bn:
    profiles: ["Hybrid", "No-EA", "No-freeze", "BN", "Hybrid-BN", "Hybrid-BN-noEA"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-nofreeze-bn
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea no-alignment --freeze no-freeze --num_exp exp_shared --dataset BNCI2014001 --remove_bn False"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-noEA-nofreeze-nobn:
    profiles: ["Hybrid", "No-EA", "No-freeze", "NoBN", "Hybrid-NoBN"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-nofreeze-nobn
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea no-alignment --freeze no-freeze --num_exp exp_shared --dataset BNCI2014001 --remove_bn True"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  hybrid-noEA-nofreeze-onebn:
    profiles: ["Hybrid", "No-EA", "No-freeze", "OneBN", "Hybrid-OneBN"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-nofreeze-onebn
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea no-alignment --freeze no-freeze --num_exp exp_shared --dataset BNCI2014001 --remove_bn One-bn"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  basic-shared-EA:
    profiles: ["Basic-Shared-EA", 'Sanity']
    extends:
      file: base.yml
      service: base-experiment
    container_name: basic-shared-ea
    command: "python src/Bruna/domain_adapt_shared_exp.py --model EEGNetShared --config config/config.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset BNCI2014001 --eval_config_file config/eval_config_shared.yaml "
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  basic-shared-NoEA:
    profiles: ["Basic-Shared-NoEA", 'Sanity']
    extends:
      file: base.yml
      service: base-experiment
    container_name: basic-shared-noea
    command: "python src/Bruna/domain_adapt_shared_exp.py --model EEGNetShared --config config/config.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset BNCI2014001 --eval_config_file config/eval_config_shared.yaml "
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  shared-EA-freeze:
    profiles: ["Shared", "EA", "Freeze", "Shared-EA-Freeze", 'Sanity']
    extends:
      file: base.yml
      service: base-experiment
    container_name: shared-ea-freeze
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNetShared --config config/config.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset BNCI2014001 --eval_config_file config/eval_config_shared.yaml "
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  shared-EA-nofreeze:
    profiles: ["Shared", "EA", "No-freeze", 'Shared-EA-NoFreeze']
    extends:
      file: base.yml
      service: base-experiment
    container_name: shared-ea-nofreeze
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNetShared --config config/config.yaml --ea alignment --freeze no-freeze --num_exp exp_shared --dataset BNCI2014001 --eval_config_file config/eval_config_shared.yaml"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  shared-noEA-freeze:
    profiles: ["Shared", "No-EA", "freeze", 'Shared-NoEA', 'Shared-NoEA-Freeze', 'Sanity']
    extends:
      file: base.yml
      service: base-experiment
    container_name: shared-noea-freeze
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNetShared --config config/config.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset BNCI2014001 --eval_config_file config/eval_config_shared.yaml"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  shared-noEA-nofreeze:
    profiles: ["Shared", "No-EA", "No-freeze", 'Shared-NoEA-NoFreeze']
    extends:
      file: base.yml
      service: base-experiment
    container_name: shared-noea-nofreeze
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNetShared --config config/config.yaml --ea no-alignment --freeze no-freeze --num_exp exp_shared --dataset BNCI2014001 --eval_config_file config/eval_config_shared.yaml"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  jupyter:
    profiles: ["jupyter"]
    #user: "0:0"
    extends:
      file: base.yml
      service: base-experiment
    container_name: jupyter-host-eeg
    command: "jupyter notebook --no-browser"
    ports:
      - "9999:8888"
    environment:
      JUPYTER_TOKEN: "docker"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '1' ]
              capabilities: [ gpu ]

  shell:
    profiles: ["shell"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: debug-shell
    command: ["/bin/bash"]
    stdin_open: true

volumes:
  moabb-datasets:
    external: true