services:
  shared-EA-freeze:
    profiles: ["Hybrid", "EA", "Freeze"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-ea-freeze
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea alignment --freeze freeze --num_exp exp_shared --dataset BNCI2014001"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  shared-EA-nofreeze:
    profiles: ["Hybrid", "EA", "No-freeze"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-ea-nofreeze
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea alignment --freeze no-freeze --num_exp exp_shared --dataset BNCI2014001"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  shared-noEA-freeze:
    profiles: ["Hybrid", "No-EA", "freeze"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-freeze
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea no-alignment --freeze freeze --num_exp exp_shared --dataset BNCI2014001"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]


  shared-noEA-nofreeze:
    profiles: ["Hybrid", "No-EA", "No-freeze"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: hybrid-noea-nofreeze
    command: "python src/Bruna/domain_adapt_exp1.py --model EEGNet --config config/config.yaml --ea no-alignment --freeze no-freeze --num_exp exp_shared --dataset BNCI2014001"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  jupyter:
    profiles: ["jupyter"]
    #user: "0:0"
    extends:
      file: base.yml
      service: base-experiment
    container_name: jupyter-host-eeg
    command: "jupyter notebook --no-browser"
    ports:
      - "9999:8888"
    environment:
      JUPYTER_TOKEN: "docker"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '1' ]
              capabilities: [ gpu ]

  shell:
    profiles: ["shell"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: debug-shell
    command: ["/bin/bash"]
    stdin_open: true

volumes:
  moabb-datasets:
    external: true