seed: 52342
train:
    num_workers: 10
    run_report: '/workspace/outputs'
    n_epochs: 1500
    patience: 300
    weight_decay: 0.01
    batch_size: 64
    lr: 0.005
    valid_split: 0.2
    experiment_name: 'full_trial_extra2'
model:
    drop_prob: 0.5
    final_conv_length: 'auto'

dataset:
    path: "/workspace/datasets/"