seed: 2342
train:
    num_workers: 10
    run_report: '/workspace/outputs/'
    n_epochs: 1000
    patience: 150
    weight_decay: 0.01
    batch_size: 64
    lr: 0.001
    valid_split: 0.2
    experiment_name: 'shared-hybridtest-batch12-bn'
model:
    drop_prob: 0.3
    final_conv_length: 'auto'

dataset:
    path: "/workspace/datasets/"